### PR TITLE
added Promise support and tests

### PR DESCRIPTION
**Pull request by LinusU**
This adds support for `Promise`s and also adds tests to the module. Run them with `npm test`.

### CODE REVIEW

**Comment by shannonmoeller** [comment]
Thanks for the pull request. After reviewing the code, I realized that there doesn't need to be a callback for module at all. Design flaw on my part. What do you think about simplifying all of this to the following:

``` js
var mute = require('mute');
var unmute = mute(); 

// Callback
app.asyncMethod(function () {
    unmute();
});

// Promise
app.asyncMethod().then(unmute, function(err) {
    unmute();
    // handle error
});
```

**Comment by shannonmoeller** [comment]
We might even allow arbitrary streams to be passed in:

``` js
var unmuteStdErr = mute(process.stderr);
```

**Comment by LinusU** [comment]
Yes, that was actually my first thought as well :)

But on the other hand, it's kind of nice to get the error handling for you. Especially when using `async`/`await`, compare

``` javascript
async function () {
  const unmute = mute()

  try {
    await myAsyncFunction()
  } catch (err) {
    unmute()
    throw err
  }

  unmute()
}
```

with

``` javascript
async function () {
  await mute(async function () {
    await myAsyncFunction()
  })
}
```

Maybe we could support the following signatures:

`mute() -> function unmute()`
`mute(fn) -> Promise`
`mute(fn, cb) -> undefined`

I think that the promise would still be the nicest to use (which promises often does), but it would have full support for people that are using callbacks instead.

``` javascript
function doItMuted (done) {
  mute(function (cb) {
    myAsyncFunction(cb)
  }, done)
}
```

The above example could propagate the error to the `cb` handler provided (`done`). This would work very good when used with mocha.

What do you think?

**Comment by LinusU** [comment]
~~The implementation would be very straight forward as well since they can use each other. e.g. the `mute(fn, cb) -> void` could be implemented in just one line: `mute(fn).then(cb, cb)`.~~

**edit:** nvm

**Comment by LinusU** [comment]
@shannonmoeller friendly ping :)

**Comment by ariporad** [comment]
@shannonmoeller: Hi! What's the chance on getting that new API implemented? It looks really nice.

**Comment by ariporad** [comment]
Ok, I've tried to implement this, but as far as I can tell, somehow process.stderr is circumvented (no idea how), because I've tried multiple modules, I've tried writing one myself, and none of them are able to stop that output. But if anyone wants to try, they're welcome.

**Comment by LinusU** [comment]
@ariporad You need to provide some more info, what do you mean `process.stderr` is circumvented?

**Comment by shannonmoeller** [comment]
I have implemented the solution that doesn't use callbacks. Because this is a synchronous operation, there is no need for callbacks or promises. Released as v2.0.3. Happy New Year!

EDIT: I also added support for passing in any number of arbitrary streams or arrays of streams:

``` js
mute(); // mutes stdout and stderr by default
mute(stream); // only mutes the given stream
mute(streamA, streamB);

var unmute =  mute([streamA, streamB], [streamC, streamD], streamE);

unmute(); // unmutes A, B, C, D, and E
```

**Comment by ariporad** [comment]
@LinusU: Sorry, that was totally the wrong issue and the wrong project. Sorry!

**Pull request closed without merging**
